language: python
python:
    - "2.7"
install:
    - pip install pyflakes
script:
    - pyflakes tests/*.py
after_success:
    - mkdir -p ~/.ssh
    - cp ./sshconfig ~/.ssh/config
    - git clone git@github.com:littleq0903/ss-ms1.git
    - cd ss-ms1
    - cat "$RAMDOM" > ./TRAVIS_COMMIT
    - git commit -am '[TRAVIS AUTOMATICALLY COMMIT]'
    - git push origin master

