after_success: 
- mkdir -p ~/.ssh
- scripts/decrypt.sh $PRIVATE_SALT ./encrypted_deploy_key.priv > ~/.ssh/id_rsa
- cp ./sshconfig ~/.ssh/config
- git clone git@github.com:littleq0903/ss-ms1.git
- ls
- cd ss-ms1
- git config user.email "travis@travis-ci.org"
- git config user.name "Travis CI"
- echo "$RANDOM" > ./TRAVIS_COMMIT
- git commit -am '[TRAVIS AUTOMATICALLY COMMIT]'
- git push origin master
install: 
- pip install pyflakes
env: 
  global: 
    secure: lUZZsRhqL8iGFZY5APtI6aQWDKEVMmCukDU2WfDvxkCZGpg4M6CGGB5Z79jy7ArKN3pkyC8ig462btYnz/O9Hdda69D5E92o4QzrAz/X2oosBQp4jB8nFGyWwf/uqWXTJz5VzgfBMBT54f0TiLSfVQyRVnwaQewB3Eec24VJIb8=
language: python
python: 
- "2.7"
script: 
- pyflakes tests/*.py
